# Builder
FROM node:22-alpine AS builder
ENV NODE_ENV=production CI=true NPM_CONFIG_LOGLEVEL=warn
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund
COPY . .
RUN npm run build

# Runner
FROM node:22-alpine AS runner
ENV NODE_ENV=production
WORKDIR /app
RUN addgroup -S appgrp && adduser -S app -G appgrp
COPY --from=builder /app/. /app
EXPOSE 3000
USER app
CMD ["node", "server.js"]
